### ISSUE TITLE
[依頼]ChatSpace挙動確認

### ISSUE THREAD

**Issue by Ligaya-yusuke** [Ligaya-yusuke/chat-space#9]
#IPアドレス
54.168.163.3

**Comment by mutorisa** [comment]
田中さん、ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○一度追加したメンバーを削除することができない為、正常にメンバーの追加や削除ができるようにしましょう。**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
**※今後実装に関する質問がありましたら、メンターに確認をお願いします！**

**Comment by Ligaya-yusuke** [comment]
> ご提出ありがとうございます！
> 確認させて頂きましたが、修正箇所問題ございませんでしたのでLGTMとさせて頂きます🎉
> おめでとうございます！
> **※今後実装に関する質問がありましたら、メンターに確認をお願いします！**

ありがとうございます。
